on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Printing'
        run: pwd

        
      - name: 'Testing Printing'
        run: echo Ahmed
